apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-practical-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-practical
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
