apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-practical.fullname" . }}
  labels:
    {{- include "devops-practical.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-practical.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "devops-practical.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: devops-practical
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
